<a href="https://colab.research.google.com/github/yerinsally/2023_PythonDataVis/blob/main/06_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- 다차원 데이터의 데이터를 쉽게 처리하도록 돕는 패키지
- 다차원 배열, 행렬의 생성과 연산, 정렬 등의 기능

In [ ]:
import numpy as np
print(np.array([1,2,3,4]))  # 1차원배열
print(np.array([[1,2,3,4],[11,12,13,14]]))  # 2차원 배열
print(np.array([[[1,2,3,4],[11,12,13,14]],[[21,22,23,24],[31,32,33,34]]]))  # 3차원 배열

[1 2 3 4]
[[ 1  2  3  4]
 [11 12 13 14]]
[[[ 1  2  3  4]
  [11 12 13 14]]

 [[21 22 23 24]
  [31 32 33 34]]]


## 다차원 배열
np.array(인자1_리스트)
- 인자1_리스트 : 가장 안쪽의 []가 넘파이 배열에서 가장 마지막 차원이 된다.

In [ ]:
# 리스트로 배열 생성
# 2차원 배열
np_array2 = np.array([[1,2,3,4],[11,12,13,14]])
print(np_array2)

# 3차원 배열
np_array3 = np.array([[[1,2,3,4],[11,12,13,14]],
                      [[21,22,23,24],[31,32,33,34]]])
print(np_array3)

# 배열의 모양 : shape
print(np_array2.shape)
print(np_array3.shape)

[[ 1  2  3  4]
 [11 12 13 14]]
[[[ 1  2  3  4]
  [11 12 13 14]]

 [[21 22 23 24]
  [31 32 33 34]]]
(2, 4)
(2, 2, 4)


In [ ]:
# 초기화 함수로 넘파이 배열 생성
z1 = np.zeros([4])  # 0으로 채운 배열
o2 = np.ones([3,4]) # 1로 채운 배열
r2 = np.random.randn(2,3) # 랜덤한 숫자 배열
z1, o2, r2

(array([0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[-0.43032298, -0.91069255,  0.51146781],
        [ 0.20137912, -1.42558782, -0.18852619]]))

In [ ]:
# 4차원 배열 생성
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 6.010e-01, -7.140e-01, -1.787e+00, -1.353e+00,  9.780e-01],
         [-1.639e+00, -2.340e-01,  2.460e-01, -1.035e+00, -7.000e-02],
         [-6.240e-01,  6.230e-01, -8.950e-01,  6.700e-01,  6.230e-01],
         [ 6.100e-02,  1.722e+00,  4.700e-02,  9.550e-01,  7.000e-02]],

        [[ 1.466e+00,  4.970e-01, -1.919e+00,  3.270e-01,  9.940e-01],
         [ 8.190e-01,  1.554e+00,  3.670e-01,  1.288e+00,  1.855e+00],
         [-1.192e+00,  7.230e-01, -8.450e-01,  6.200e-02,  1.280e-01],
         [ 2.300e-01,  1.327e+00, -8.430e-01, -1.360e-01, -4.480e-01]]],


       [[[ 3.020e-01, -7.190e-01, -1.312e+00, -5.440e-01, -2.227e+00],
         [ 2.820e-01, -5.840e-01,  3.770e-01, -2.530e-01, -3.910e-01],
         [ 9.630e-01, -1.137e+00,  4.500e-01, -1.000e-03,  1.200e-02],
         [-1.056e+00, -1.383e+00, -6.460e-01,  1.880e-01,  1.330e+00]],

        [[-1.630e-01,  5.610e-01, -3.920e-01, -1.814e+00,  3.700e-01],
         [-1.067e+00, -1.250e-01, -3.070e-01,  1.590e-01,  1.085e+00]

## Indexing & Slicing

In [ ]:
# r4 배열 : [두번째][첫번째] 접근해서 가져오기
print(r4[1][0])
print(r4[1][0][2])
print(r4[1][0][2][4])
print(r4[1,0,2,4])  # 대괄호 대신 콤마도 차원 접근 가능

[[ 3.020e-01 -7.190e-01 -1.312e+00 -5.440e-01 -2.227e+00]
 [ 2.820e-01 -5.840e-01  3.770e-01 -2.530e-01 -3.910e-01]
 [ 9.630e-01 -1.137e+00  4.500e-01 -1.000e-03  1.200e-02]
 [-1.056e+00 -1.383e+00 -6.460e-01  1.880e-01  1.330e+00]]
[ 9.630e-01 -1.137e+00  4.500e-01 -1.000e-03  1.200e-02]
0.012
0.012


In [ ]:
# 슬라이싱
print(r4[1][0][0:4:2])
print(r4[1][0][1:4:2])

# 인덱싱, 슬라이싱 같이 적용하기
print(r4[1][0][1:4:2][1][3:])

[[ 3.020e-01 -7.190e-01 -1.312e+00 -5.440e-01 -2.227e+00]
 [ 9.630e-01 -1.137e+00  4.500e-01 -1.000e-03  1.200e-02]]
[[ 0.282 -0.584  0.377 -0.253 -0.391]
 [-1.056 -1.383 -0.646  0.188  1.33 ]]
[0.188 1.33 ]


In [ ]:
# 배열 간 연산
arr = np.array([[1,2,3,4],[10,11,12,13]])
print(arr + arr)

# Broadcasting 연산
print(arr + 20)
print(arr * 100)

[[ 2  4  6  8]
 [20 22 24 26]]
[[21 22 23 24]
 [30 31 32 33]]
[[ 100  200  300  400]
 [1000 1100 1200 1300]]


In [ ]:
# Aggregation : 넘파이 배열에 대해 모든 원소 집계하는 연산
print(arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min())

# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
print(arr.argmax(), arr[1].argmax(), arr.argmin())

# 특정 축으로 덧셈 수행
print(arr.sum(axis=0), arr.sum(axis=1))

# Indexing & Slicing & Aggregation
print(arr[1].min(), arr[1][2:].sum())

56 7.0 411840 13 1
7 3 0
[11 13 15 17] [10 46]
10 25


In [ ]:
# 고급 Broadcasting
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
print(arr1.shape, arr2.shape)

print(arr1 + arr2)
print(arr1 + np.array([0,1,2])) # (4X3) + (1X3)
print(np.array([[0],[10],[20],[30]]) + np.array([0,1,2])) # (4X1) + (1X3)

(4, 3) (4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# Pandas
- 1~2차원 표 형태의 데이터
- 행과 열에 이름을 붙일 수 있음

## Series
- 행 X 값 데이터
- 1차원 데이터를 잘 표현함

In [ ]:
# Series 출력
import pandas as pd
import numpy as np

index = ['a', 'b', 'c', 'd', 'e', 'f']
my_series = pd.Series(np.random.rand(6), index=index)
my_series

a    0.596250
b    0.401723
c    0.904681
d    0.767353
e    0.399973
f    0.161715
dtype: float64

In [ ]:
# 인덱스와 이름 보기
print(my_series.index)
print(my_series.name)

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')
None


In [ ]:
# Slicing : .loc & .iloc
print(my_series.loc['b'])
print(my_series.iloc[4])
print(my_series.iloc[4:6])

0.4017232998062249
0.39997333244953703
e    0.399973
f    0.161715
dtype: float64


- .loc : 인덱스를 이용, 일부를 추출, 끝을 포함
- .iloc : 배열번호를 이용, 일부를 추출, 끝을 포함X

In [ ]:
# Series 연산 : Broadcasting
print(my_series.iloc[4:] + my_series.iloc[4:])
print(my_series.loc['b'::2] + 30)

e    0.799947
f    0.323430
dtype: float64
b    30.401723
d    30.767353
f    30.161715
dtype: float64


In [ ]:
# Aggregation
my_series.iloc[4:].mean()

0.28084428063824873

## Dataframe
- 2차원 데이터를 잘 다루기 위해 만든다
- 여러 개의 Series를 묶어서 만든 형태

In [ ]:
import pandas as pd
import numpy as np


# 임의의 값을 가지는 6개의 열(column) 생성
data = np.random.rand(10000, 6)

# 데이터프레임 생성
my_df = pd.DataFrame(data, columns=['col1', 'col2', 'col3', 'col4', 'col5', 'col6'])

# 결과 확인
my_df

col1      col2      col3      col4      col5      col6
0     0.201085  0.000488  0.446632  0.904962  0.762049  0.578763
1     0.316288  0.279243  0.973143  0.177220  0.548947  0.621673
2     0.006840  0.772093  0.110612  0.686555  0.753640  0.233685
3     0.973987  0.409143  0.776717  0.541838  0.112562  0.594712
4     0.789472  0.297827  0.914082  0.189953  0.895012  0.103588
...        ...       ...       ...       ...       ...       ...
9995  0.105089  0.740626  0.030219  0.340826  0.301719  0.013156
9996  0.949459  0.790176  0.788357  0.634414  0.388958  0.835366
9997  0.241324  0.760169  0.811489  0.874570  0.619239  0.097485
9998  0.499262  0.744648  0.299509  0.020809  0.749399  0.443982
9999  0.150196  0.499592  0.348524  0.854607  0.552479  0.718417

[10000 rows x 6 columns]

In [ ]:
# Indexing & Slicing 접근 시, 접근 결과 1차원이면 Series 반환
print(my_df.loc[4,'col2'])
print(my_df.loc[4,'col2':'col5'])

# Indexing & Slicing 접근 시, 접근 결과 2차원이면 Series 반환
print(my_df.loc[4:8:2, 'col2':'col5'])

0.7147391474759154
col2    0.714739
col3    0.629748
col4    0.609233
col5    0.616235
Name: 4, dtype: float64
       col2      col3      col4      col5
4  0.714739  0.629748  0.609233  0.616235
6  0.266960  0.668296  0.367124  0.067873
8  0.968421  0.884647  0.613409  0.618156


In [ ]:
# .iloc 접근
print(my_df.iloc[0,3:])
print(my_df.iloc[4:7:2, 1:4])

col4    0.533000
col5    0.536241
col6    0.575249
Name: 0, dtype: float64
       col2      col3      col4
4  0.714739  0.629748  0.609233
6  0.266960  0.668296  0.367124


In [ ]:
# : 로 모든 원소 지칭하기
my_df.loc[::, 'col3']

0       0.446632
1       0.973143
2       0.110612
3       0.776717
4       0.914082
          ...   
9995    0.030219
9996    0.788357
9997    0.811489
9998    0.299509
9999    0.348524
Name: col3, Length: 10000, dtype: float64

In [ ]:
# Broadcasting
my_df_2 = my_df.loc[:5000,'col4':]
my_df_2

my_df_2 * 3

col4      col5      col6
0     2.714886  2.286146  1.736289
1     0.531659  1.646841  1.865019
2     2.059666  2.260920  0.701054
3     1.625513  0.337685  1.784136
4     0.569860  2.685037  0.310764
...        ...       ...       ...
4996  1.746219  0.883169  1.450158
4997  0.367732  1.959153  1.956103
4998  2.618897  0.775868  0.468437
4999  0.206822  1.927184  2.931043
5000  2.841804  0.401329  1.385310

[5001 rows x 3 columns]

In [ ]:
# Aggregation
print(my_df_2.mean(axis=0))

# 연산
print(my_df_2.notna())

col4    0.495576
col5    0.503789
col6    0.503598
dtype: float64
      col4  col5  col6
0     True  True  True
1     True  True  True
2     True  True  True
3     True  True  True
4     True  True  True
...    ...   ...   ...
4996  True  True  True
4997  True  True  True
4998  True  True  True
4999  True  True  True
5000  True  True  True

[5001 rows x 3 columns]


연산 총 정리
- .abs() = 절댓값, .isna() = na여부, .notna() = 유효여부, .pow() = 거듭제곱

In [ ]:
# 축 방향 연산 : axis=0 or 1
print(my_df_2.sum(axis=0))
print(my_df_2.median(axis=1))

col4    2478.377591
col5    2519.449685
col6    2518.491804
dtype: float64
0       0.762049
1       0.548947
2       0.686555
3       0.541838
4       0.189953
          ...   
4996    0.483386
4997    0.652034
4998    0.258623
4999    0.642395
5000    0.461770
Length: 5001, dtype: float64


- mean, median, max, min, sum, prod = 곱하기, idmax = 최대원소의 인덱스, idmin = 최소원소의 인덱스

In [ ]:
# 누적 축 방향 연산
my_df_2.cumsum(axis=0)

col4         col5         col6
0        0.904962     0.762049     0.578763
1        1.082181     1.310996     1.200436
2        1.768737     2.064636     1.434121
3        2.310574     2.177197     2.028833
4        2.500528     3.072209     2.132421
...           ...          ...          ...
4996  2476.365839  2517.761840  2516.244839
4997  2476.488416  2518.414891  2516.896874
4998  2477.361382  2518.673514  2517.053020
4999  2477.430322  2519.315908  2518.030034
5000  2478.377591  2519.449685  2518.491804

[5001 rows x 3 columns]

- cummax, cummin, cumprod, cumsum

In [ ]:
# 정렬 : sort_values(정렬기준, axis = 축, ascending = True)
my_df_2.sort_values(4, axis='columns', ascending=True)

col6      col4      col5
0     0.578763  0.904962  0.762049
1     0.621673  0.177220  0.548947
2     0.233685  0.686555  0.753640
3     0.594712  0.541838  0.112562
4     0.103588  0.189953  0.895012
...        ...       ...       ...
4996  0.483386  0.582073  0.294390
4997  0.652034  0.122577  0.653051
4998  0.156146  0.872966  0.258623
4999  0.977014  0.068941  0.642395
5000  0.461770  0.947268  0.133776

[5001 rows x 3 columns]

In [ ]:
# rank : 특정 axis 기준으로 랭킹 매기기
my_df_2.rank(axis=0, ascending=False)

col4    col5    col6
0      466.0  1205.0  2129.0
1     4100.0  2308.0  1925.0
2     1514.0  1253.0  3825.0
3     2234.0  4427.0  2051.0
4     4029.0   536.0  4501.0
...      ...     ...     ...
4996  2034.0  3547.0  2600.0
4997  4395.0  1771.0  1780.0
4998   619.0  3715.0  4248.0
4999  4653.0  1818.0   118.0
5000   250.0  4300.0  2716.0

[5001 rows x 3 columns]

In [ ]:
# 새로운 행,열 추가하기
my_df_2.loc[:,'new'] = np.nan   # 새로운 열 추가
my_df_2.loc[:,'new'] = range(0,5001)  # 새로운 행 추가
my_df_2.loc[:,'new2'] = 1 # 숫자 하나만 주면 broadcast 됨
my_df_2

<ipython-input-55-51314dd88359>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  my_df_2.loc[:,'new'] = range(0,5001)  # 새로운 행 추가


col4      col5      col6   new  new2
0     0.904962  0.762049  0.578763     0     1
1     0.177220  0.548947  0.621673     1     1
2     0.686555  0.753640  0.233685     2     1
3     0.541838  0.112562  0.594712     3     1
4     0.189953  0.895012  0.103588     4     1
...        ...       ...       ...   ...   ...
4996  0.582073  0.294390  0.483386  4996     1
4997  0.122577  0.653051  0.652034  4997     1
4998  0.872966  0.258623  0.156146  4998     1
4999  0.068941  0.642395  0.977014  4999     1
5000  0.947268  0.133776  0.461770  5000     1

[5001 rows x 5 columns]

## 참고
- concat : 데이터프레임 병합
  - 0 또는 index : 행 방향 병합
  - 1 또는 column : 열 방향 병합

```
df.concat([df_a, df_b]), axis = 0/1)
```


- groupby : 특정 인덱스, 컬럼의 값별로 그룹핑하여 Aggregation 수행
  - Aggregation : sum(), count(), mean(), max() 등


```
groupby(by = 집계대상, axis = 집계축).Aggregation
```

- query : 작성한 쿼리문으로 dataframe 필터링하여 추출


```
my_df.query('col1' == 'A' and 'col2' > 10)
```

- set_index, reset_index : 인덱스를 잡거나 푼다
- fillna : NaN 결측치를 채운다 (method 인자)
- drop : 특정 row, column 지우는 함수


```
my_df.drop(index = [지울 인덱스], columns = [지울 컬럼])
my_df.dropna(axis = 0, how = 'any')
```
